name: my_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  mobile_scanner: ^6.0.10
  camera: ^0.11.0+2
  permission_handler: ^11.2.0
  google_mlkit_barcode_scanning: ^0.14.0
  google_mlkit_commons: ^0.10.0


  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

<<<<<<< HEAD:pubspec.yaml
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    
=======
  

  # To add assets to your application, add an assets section, like this:
  assets:   
    - assets/C1.jpg
    - assets/C2.jpg
    - assets/C3.jpg
    - assets/C4.jpg
    - assets/C5.jpg
    - assets/C6.jpg
    - assets/C7.jpg
    - assets/C8.jpg
    - assets/logo.png
    

   
    
>>>>>>> 0bf0a24289786e9b5bf5e970cdae455522e9c6e1:my_app/pubspec.yaml
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
